#!/bin/sh

SHORTDATE=`date "+%m-%d-%Y"`

# current version number
CURRENTVERSION=2.9.3

# last date
LASTDATE=06-23-2014

if [ "x$1" = "x" ]
then
        echo "Usage: $0 <version number>"
        echo ""
        echo "Run this script with the name of the new version (i.e \"2.6\") to"
        echo "update version number."
        echo ""
        echo "Current version=$CURRENTVERSION"
        echo "Current modification date=$LASTDATE"
        echo ""
        exit 1
fi

# update version number in common code
perl -i -p -e "s/VERSION \".*\"/VERSION \"$1\"/;" include/common.h
perl -i -p -e "s/MODIFICATION_DATE \".*\"/MODIFICATION_DATE \"$SHORTDATE\"/;" include/common.h
perl -i -p -e "s/Last Modified: [0-9].*/Last Modified: $SHORTDATE/;" include/common.h

# update version number and release date in configure script and configure.in
perl -i -p -e "s/PKG_VERSION=.*/PKG_VERSION=\"$1\"/;" configure
perl -i -p -e "s/PKG_REL_DATE=.*\"/PKG_REL_DATE=\"$SHORTDATE\"/;" configure
perl -i -p -e "if( /^AC_INIT/) { s/$CURRENTVERSION/$1/; }" configure.in
perl -i -p -e "s/PKG_VERSION=.*/PKG_VERSION=\"$1\"/;" configure.in
perl -i -p -e "s/PKG_REL_DATE=.*\"/PKG_REL_DATE=\"$SHORTDATE\"/;" configure.in

# update RPM spec file with version number
perl -i -p -e "s/%define version .*/%define version $1/;" nsca.spec

# update this file with version number and last date
perl -i -p -e "s/^CURRENTVERSION=.*/CURRENTVERSION=$1/;" update-version
perl -i -p -e "s/^LASTDATE=.*/LASTDATE=$SHORTDATE/;" update-version
